steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    id: GET_SETTINGS
    args: ['cp', 'gs://salus-mavenrepository/m2-settings.xml', '.mvn/settings.xml']
  - name: 'gcr.io/cloud-builders/mvn'
    id: compile
    args: ['compile', '.mvn/settings.xml']
  - name: 'gcr.io/cloud-builders/mvn'
    id: DEPLOY
    args: ['-B', 'deploy', '-s', '.mvn/settings.xml']