substitutions:
  _APP_NAME: e2e
  _APP_NAMESPACE: default
  _CLOUDSDK_COMPUTE_ZONE: us-east1-b
  _CLOUDSDK_CONTAINER_CLUSTER: salus-dev

steps:
  # using Docker build caching https://cloud.google.com/cloud-build/docs/kaniko-cache
  - name: 'gcr.io/kaniko-project/executor:v0.16.0'
    id: COMPILE_AND_PUSH_CONTAINER
    args:
      - --context=/workspace/e2et
      - --destination=gcr.io/$PROJECT_ID/salus-e2e
      - --cache=true

  - name: gcr.io/cloud-builders/git
    id: HELM_CLONE
    waitFor:
    - COMPILE_AND_PUSH_CONTAINER
    args: ['clone', 'https://source.developers.google.com/p/$PROJECT_ID/r/github_rackspace-segment-support_helm-salus-${_APP_NAME}', '/workspace/helm-salus-${_APP_NAME}/']

  # Set _CLOUDSDK_COMPUTE_REGION in the build trigger for non-dev clusters
  - name: 'gcr.io/$PROJECT_ID/helm'
    id: DEPLOY_APPLICATION
    waitFor:
      - HELM_CLONE
    args: ['upgrade', '--install', '${_APP_NAME}', '--namespace', '${_APP_NAMESPACE}', '/workspace/helm-salus-${_APP_NAME}']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    - 'TILLERLESS=true'

options:
    substitution_option: 'ALLOW_LOOSE'
