mode: dev
regular.id: <normal rackspace user name>
tenant.id: <rackspace tenant id>
public.api.url:  <dev public api>
admin.api.url:  <dev admin api>
kafka.brokers: <dev kafka broker>
event.topic:  <dev kafka topic>
cert.file: <kafka client cert file>
ca.file: <kafka ca file>
key.file: <kafka client key file>
identity.url: <keystone/identity url>
auth.url: <dev auth service url>
ambassador.address: <dev ambassador address>
event.timeout: 5m
envoy.tarball.linux: https://github.com/racker/salus-telemetry-envoy/releases/download/0.13.0/telemetry-envoy_0.13.0_Linux_x86_64.tar.gz
envoy.tarball.darwin: https://github.com/racker/salus-telemetry-envoy/releases/download/0.13.0/telemetry-envoy_0.13.0_Darwin_x86_64.tar.gz
telegraf.version: 1.13.2
